name: Bug Report
description: An issue with petit-filou
labels: ["bug", "triage"]
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Before submitting a bug repport
      options:
        - label: Check [discussions](https://github.com/petit-chat/petit-filou/discussions).
          required: true
        - label: Check [open](https://github.com/petit-chat/petit-filou/issues) and [rejected](https://github.com/petit-chat/petit-filou/labels/wontfix) issues.
          required: true
  - type: input
    id: version
    attributes:
      label: What version of petit-filou are you running?
      description: Can be found running `petit-filou --version`.
    validations:
      required: true
  - type: dropdown
    id: operating-systems
    attributes:
      label: What OS are you reproducing the problem on?
      multiple: true
      options:
        - Linux
        - macOS
        - Windows
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
