name: Feature Request
description: Suggest an idea for petit-filou
title: "[Feat]: "
labels: ["enhancement", "triage"]
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Before submitting a bug repport
      options:
        - label: Check [discussions](https://github.com/petit-chat/petit-filou/discussions).
          required: true
        - label: Check [open](https://github.com/petit-chat/petit-filou/issues) and [rejected](https://github.com/petit-chat/petit-filou/labels/wontfix) issues.
          required: true
  - type: input
    id: version
    attributes:
      label: What version of petit-filou are you running?
      description: Can be found running `petit-filou --version`.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What feature would you like to see for petit-filou?
      description: Describe your feature request and expected behaviour.
      placeholder: Tell us what you want!
    validations:
      required: true
