name: Build binaries

permissions:
  contents: write

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-release-binaries:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
          - os: ubuntu-latest
            target: i686-unknown-linux-gnu
          - os: ubuntu-latest
            target: i686-unknown-linux-musl
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - os: windows-latest
            target: i686-pc-windows-msvc
          - os: windows-latest
            target: x86_64-pc-windows-gnu
          - os: windows-latest
            target: x86_64-pc-windows-msvc
      fail-fast: false
    steps:
      - uses: actions/checkout@v4    
      - name: Build and upload assets
        uses: taiki-e/upload-rust-binary-action@main
        with:
          archive: $bin-${{ github.event.release.name }}-$target
          bin: pf
          checksum: sha256
          include: README.md,CHANGELOG.md,LICENSE
          leading-dir: true
          target: ${{ matrix.target }}
          token: ${{ secrets.GITHUB_TOKEN }}
