name: Continuous Deployment

on:
  workflow_dispatch:

jobs:
  prepare-release:
    name: Prepare Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.VERSION }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Up git-cliff
        uses: kenji-miyake/setup-git-cliff@v2

      - name: Get Version
        id: get-version
        run: |
          BUMPED_VERSION=$(git cliff --bumped-version)
          echo "VERSION=${BUMPED_VERSION#v}" >> "$GITHUB_OUTPUT"

      - name: Generate Changelog
        run: |
          git cliff --bump --output CHANGELOG.md --no-exec --github-repo ${{ github.repository }}

      - name: Update Version
        run: |
          sed -E -i "s/^version = \"[0-9\.]+\"$/version = \"${{ env.VERSION }}\"/" Cargo.toml
          sed -E -i "s/^[0-9\.]+$/${{ env.VERSION }}/" README.md
        env:
          VERSION: ${{ steps.get-version.outputs.VERSION }}
          
      - name: Commit Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "actions[bot]"
          git add Cargo.toml Cargo.lock CHANGELOG.md README.md
          git commit -m "chore(release): v${{ env.VERSION }}"
          git push
        env:
          VERSION: ${{ steps.get-version.outputs.VERSION }}

      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          draft: true
          ref: refs/tags/v${{ env.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          VERSION: ${{ steps.get-version.outputs.VERSION }}

  build-and-upload-assets:
    name: Build and Upload Assets
    needs: prepare-release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: universal-apple-darwin
            os: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      
      - name: Build and Upload Assets
        uses: petit-chat/upload-rust-binary-action@main
        with:
          archive: petit-filou-$tag-$target
          bin: petit-filou,generate-completions,generate-man
          run: generate-completions,generate-man
          checksum: sha256
          include: README.md,CHANGELOG.md,LICENSE,completions,man
          leading-dir: true
          ref: refs/tags/v${{ env.VERSION }}
          target: ${{ matrix.target }}
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          VERSION: ${{ needs.prepare-release.outputs.version }}

  publish-release:
    name: Publish Release
    needs: [prepare-release, build-and-upload-assets]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Publish Release
        run: |
          gh release edit v${{ env.VERSION }} --draft=false
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ needs.prepare-release.outputs.version }}
