name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-D warnings"
  RUSTDOCFLAGS: "-D warnings"

jobs:
  audit:
    name: Audit Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Audit Rust Dependencies
        uses: actions-rust-lang/audit@v1

  broken-links:
    name: Check for Broken Links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check the links
        uses: lycheeverse/lychee-action@v1
        with:
          fail: true
          token: ${{ secrets.GITHUB_TOKEN }}

  doc:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Doc
        run: cargo doc

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      
      - name: Install Tarpaulin
        run: |
          cargo install cargo-tarpaulin --git https://github.com/xd009642/tarpaulin

      - name: Run Tarpaulin
        run: |
          cargo tarpaulin --all-features --coveralls ${{ secrets.COVERALLS_REPO_TOKEN }}

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Check Formatting
        run: cargo fmt -- --check

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Lint
        run: cargo clippy
  
  lockfile:
    name: Check Lockfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Check Lockfile
        run: cargo fetch --locked

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Compile
        run: cargo test --no-run --locked

      - name: Test
        run: cargo test -- --nocapture --quiet

  typos:
    name: Check Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Typos
        uses: crate-ci/typos@master