name: Dependabot auto-merge
on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Auto-merge Dependabot PRs
        run: gh pr merge -s ${{ github.event.pull_request.html_url }}
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
