name: Dependabot auto-merge
on:
  pull_request:
    branches:
      - main

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Auto-merge Dependabot PRs
        run: gh pr merge --auto -s ${{ github.event.pull_request.html_url }}
        env:
          # Use custom token here to allow triggering other
          # pipelines (e.g. binary builds) after release.
          GH_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN }}
