name: Build Docker

permissions:
  contents: read
  packages: write

on:
  release:
    types: [published]

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{github.actor}}
            password: ${{secrets.GITHUB_TOKEN}}
      - name: Build and push Docker image
        run: |
          docker build . --tag ghcr.io/petit-chat/pf:${{ github.event.release.name }}
          docker push ghcr.io/petit-chat/pf:${{ github.event.release.name }}
