name: Check for Broken Links

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  broken-links:
    name: Check for Broken Links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check the links
        uses: lycheeverse/lychee-action@v2
        with:
          fail: true
