name: Nightly

on:
  schedule:
    - cron: '45 6 * * *'
  workflow_dispatch:

jobs:
  release-nightly:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Nightly cleanup
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete nightly --yes --cleanup-tag || true
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /users/petit-chat/packages/docker/pf/versions/nightly \
            || true
      - name: Release nightly
        env:
          GH_TOKEN: ${{ secrets.NIGHTLY_BUILD_TOKEN }}
        run: |
          gh release create nightly --title nightly --generate-notes --prerelease
