name: Nightly

on:
  schedule:
    - cron: '45 6 * * *'
  workflow_dispatch:

jobs:
  release-nightly:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Release nightly
        env:
          GH_TOKEN: ${{ secrets.NIGHTLY_BUILD_TOKEN }}
        run: |
          gh release delete nightly --yes --cleanup-tag || true
          gh release create nightly --title nightly --generate-notes --prerelease
